# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d9c9cbe6b15f08ab911bd039286f822a23e350ca40a868c45d69c163c509db65857785d9446faa6a8dfd1760b27571811f1d4fbb86d7f5edf5c7fa63c69e81d

test:
  secret_key_base: 5f2bee70c8ac362ded2a28190612d6ce0519aac935b26658128936f8025c00b2139adf39c3cff0b609681385262d577e7cb80430f36582ce555e050d95994d13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
